# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

# Configuration for Vercel deployment - PRODUCTION
client_id = "876289cfbb8474b45386415b86fa5be4"
name = "elektro3-api-integration"
handle = "elektro3-api-integration"
application_url = "https://elektro3-api-integration-3rtt7qtzr-electro-malho.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_customers,read_customers,write_orders,read_orders"

[auth]
redirect_urls = [
  "https://elektro3-api-integration-3rtt7qtzr-electro-malho.vercel.app/auth/callback",
  "https://elektro3-api-integration-3rtt7qtzr-electro-malho.vercel.app/auth/shopify/callback",
  "https://elektro3-api-integration-3rtt7qtzr-electro-malho.vercel.app/api/auth/callback"
]

[pos]
embedded = false
