# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "876289cfbb8474b45386415b86fa5be4"
name = "elektro3-api-integration"
handle = "elektro3-api-integration"
application_url = "https://beef-gothic-teachers-visits.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_customers,write_orders,write_products"

[auth]
redirect_urls = [
  "https://beef-gothic-teachers-visits.trycloudflare.com/auth/callback",
  "https://beef-gothic-teachers-visits.trycloudflare.com/auth/shopify/callback",
  "https://beef-gothic-teachers-visits.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
