# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4cf8390b0636456a82bab4017d681cba"
name = "Elektro3 Integração"
handle = "elektro3-api-integration"
application_url = "https://elektro3-api-integration-electro-malho.vercel.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_customers,read_customers,write_orders,read_orders"

[auth]
redirect_urls = [
  "https://elektro3-api-integration-electro-malho.vercel.app/auth/callback",
  "https://elektro3-api-integration-electro-malho.vercel.app/auth/shopify/callback",
  "https://elektro3-api-integration-electro-malho.vercel.app/api/auth/callback",
  "http://localhost:3000/auth/callback",
  "http://localhost:3000/auth/shopify/callback",
  "http://localhost:3000/api/auth/callback",
  "http://localhost:30001/auth/callback",
  "http://localhost:30001/auth/shopify/callback",
  "http://localhost:30001/api/auth/callback"
]

[pos]
embedded = false