# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

# Using environment variables for Vercel deployment
client_id = "${env.SHOPIFY_API_KEY}"
name = "elektro3-api-integration"
handle = "elektro3-api-integration"
application_url = "${env.SHOPIFY_APP_URL}"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "${env.SCOPES}"

[auth]
redirect_urls = [
  "${env.SHOPIFY_APP_URL}/auth/callback",
  "${env.SHOPIFY_APP_URL}/auth/shopify/callback",
  "${env.SHOPIFY_APP_URL}/api/auth/callback"
]

[pos]
embedded = false
