# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ae8937bac07720749eeec3a91647f722"
name = "elektro3-api-module"
handle = "elektro3-api-module"
application_url = "https://reprints-might-investing-specially.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://reprints-might-investing-specially.trycloudflare.com/auth/callback",
  "https://reprints-might-investing-specially.trycloudflare.com/auth/shopify/callback",
  "https://reprints-might-investing-specially.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
